// prefijo far
export {
  faChevronDown as farChevronDown,
  faChevronUp,
  faExclamationCircle,
  faCheckCircle,
  faMars,
  faVenus,
  faCheck as farCheck,
  faPaperclip as farPaperClip,
  faExclamationTriangle,
  faSearch as farSearch,
  faEllipsisV as farEllipsisV,
  faCopy as farCopy,
  faTimes,
  faTimesCircle,
  faMoneyBillAlt as farMoneyBillAlt,
  faArrowLeft as farArrowLeft,
  faArrowRight as farArrowRight,
  faArrowAltToBottom,
} from '@fortawesome/pro-regular-svg-icons';
