// prefijo fas
export {
  faUserSecret,
  faHome,
  faPaperPlane,
  faTicketAlt,
  faWallet,
  faGift,
  faQuestionCircle,
  faInfoCircle,
  faUserPlus,
  faUserTimes,
  faTimesCircle,
  faCheckCircle as fasCheckCircle,
  faFileSignature,
  faEdit,
  faTrash,
  faPlusCircle as fasPlusCircle,
  faChevronRight as fasChevronRight,
  faChevronLeft as fasChevronLeft,
  faMoneyBillWave,
  faHandHoldingUsd,
  faLongArrowAltLeft,
  faFileInvoiceDollar,
  faUndoAlt,
  faCreditCard,
  faEllipsisV,
  faBullhorn,
  faFileAlt,
  faMars,
  faVenus,
  faUsers,
  faBuilding,
  faMoneyCheckAlt,
  faLock,
  faQuestion,
  faAngleDown as fasAngleDown,
  faDownload as fasDownload,
  faSearch as fasSearch,
  faSave,
  faFileExcel as fasFileExcel,
  faUserSlash,
  faExclamationTriangle,
  faSort,
  faTrashAlt,
  faCaretDown,
} from '@fortawesome/free-solid-svg-icons';
