// prefijo fas
export {
  faExclamationTriangle,
  faUsdCircle,
  faUser,
  faSignOut,
  faArrowRight,
  faArrowLeft,
  faExchange,
  faExternalLinkSquareAlt,
  faUserEdit,
  faFileImage as fasFileImage,
  faUpload as fasUpload,
  faFileWord as fasFileWord,
  faFilePdf as fasFilePdf,
  faFile as fasFile,
  faExclamationCircle as fasExclamationCircle,
  faCheck as fasCheck,
  faSortAlt as fasSortAlt,
  faLock as fasLock,
  faLongArrowAltRight,
  faLongArrowAltLeft,
  faDollarSign,
  faMinus,
  faEquals,
  faTimes,
  faCircle,
  faAsterisk,
  faCopy as fasCopy,
  faMinusCircle as fasMinusCircle,
  faPaperPlane as fasPaperPlane,
  faUsersMedical,
  faExclamation,
  faInfoCircle as fasInfoCircle,
  faHandPaper,
  faCamera,
  faUndo,
  faSave,
  faUserCog,
  faDotCircle as fasDotCircle,
  faEye,
  faEyeSlash,
} from '@fortawesome/pro-solid-svg-icons';
